### ISSUE TITLE
Add Puzzle ITC

### ISSUE THREAD

**Issue by gcomte** [brettpullen/bitcoinsalary.com#1]
Name: **Puzzle ITC**
Total number of employees accepting a salary in Bitcoin: **20**
Total number of employees: **145**
Jurisdiction: **Switzerland**
Credible filing or announcement link: **[Article](https://www.bernerzeitung.ch/region/bern/bitcoins-in-der-lohntuete/story/28988765) [German], [Another Article](https://www.inside-it.ch/de/post/puzzle-itc-will-loehne-teilweise-mit-bitcoin-auszahlen-20180206) [German], [TV News](https://www.rts.ch/play/tv/19h30/video/coinbase-est-la-premiere-entreprise-consacree-aux-cryptomonnaies-a-entrer-a-wall-street-?urn=urn:rts:video:12124402) [French], I am an [employee](https://www.puzzle.ch/de/blog/articles/author/gcomte) myself**
Link to the organizations current job openings: **https://www.puzzle.ch/de/ueber-uns/stellen [German]**

**Comment by brettpullen** [comment]
Thank you, Gabriel. I just added Puzzle ITC to BitcoinSalary.com.  As it has been 3 months, please respond back if you have updated numbers for total employees and/or total number accepting BTC.

**Comment by KramNamez** [comment]
Hi Brett,
as of this summer Puzzle no longer pays out (parts of) salaries in Bitcoin. Could you please remove us from the list?
